---
apiVersion: v1
kind: Service
metadata:
  name: microservice-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  replicas: 10
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: regcbu.azurecr.io/microservice/microservice:latest
        resources:
          limits:
            memory: 170Mi
            cpu: "100m"
          requests:
            memory: 100Mi
            cpu: "70m"
        ports:
        - containerPort: 80
